http:
  port: 80
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  webRoot:
    host: '*'
    paths:
      - '/'
    methos: ['GET']     
  sockjsnode:
    host: '*'
    paths:
      - '/sockjs-node/**'
    methos: ['GET', 'POST']     
  staticContent:
    host: '*'
    paths:
      - '**/*.*'   
    methos: ['GET']  
  default:
    host: '*'
    paths:
      - '**'   
    methos: ['GET']   
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  staticContent:
    url: "${ENV_STATIC_CONTENT_ROOT:-http://localhost:4200}"
  default:
    url: "${ENV_STATIC_CONTENT_ROOT:-http://localhost:4200}/index.html"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  webRoot:
    apiEndpoints:
      - webRoot
    policies:
      - rewrite:
          - 
            condition:
              name: pathmatch
              match: /
            action:
              rewrite: /index.html
      - proxy:
          - action: 
              serviceEndpoint: staticContent
  staticContent:
    apiEndpoints:
      - staticContent
      - sockjsnode
    policies:
      - proxy:
          - action: 
              serviceEndpoint: staticContent
  default:
    apiEndpoints:
      - default
    policies:
      - proxy:
          - action: 
              ignorePath: true
              serviceEndpoint: default
