http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  webRoot:
    host: '*'
    paths:
      - '/'
    methos: ['GET']   
  webClient:
    host: '*'
    paths:
      - '**'   
    methos: ['GET']   
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  webClient:
    url: "${ENV_STATIC_CONTENT_ROOT:-http://localhost:4200/}"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - rewrite
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  webRoot:
    apiEndpoints:
      - webRoot
    policies:
      - rewrite:
          - 
            condition:
              name: pathmatch
              match: /
            action:
              rewrite: /index.html
              redirect: 302
  webClient:
    apiEndpoints:
      - webClient
    policies:
      - proxy:
          - action: 
              serviceEndpoint: webClient
