http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
  webClient:
    host: '*'
    paths:
      - '**'      
serviceEndpoints:
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
  webClient:
    url: http://localhost:4200
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
  webClient:
    apiEndpoints:
      - webClient
    policies:
      - proxy:
          - action: 
              serviceEndpoint: webClient
